title: Nick Pisor # your name (or website title) here
logo: "/images/face.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior IST Major, Penn State University
  <br><br>
  Java and Python Developer, Experienced in Android Studio
  <br><br>
  I've worked as an operating engineer in Heavy Civil Construction while pursuing my degree
  in Information Sciences and Technology with an emphasis on application and design.
  <a href="https://www.linkedin.com/in/nickpisor/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
